// src/app/app.component.ts
import { AfterViewInit, Component, HostListener, NgZone, OnDestroy } from '@angular/core';

import * as Tone from 'tone'
import { WebMidi, type NoteMessageEvent } from "webmidi";

import { Synthesizer, type ISynthesizerSerialization } from './synthesizer/synthesizer'
import { Storage } from './core/storage'
import { G } from './globals'

import { Visual } from './p5/visual'

import { DEFAULT_SESSION } from './synthesizer/presets';
import { Midi } from './core/midi';
import { isSafari } from './util/browser';

import { COLORS } from './core/colors';
import { DB } from './core/db';
import { SynthesizerComponent } from './view/Synthesizer.component';
import { MenuComponent } from './view/Menu.component';
import { CommonModule } from '@angular/common';
import { BeatMachine } from './synthesizer/beat-machine';


@Component({
  selector: 'app-root',
  standalone: true,
  imports: [ CommonModule, SynthesizerComponent, MenuComponent],
  template: `
  
  

  <div class="app-wrapper">

    <sy-menu [isActive]="isMenuOpen" (onClose)="toggleMenu($event)" />

    <div class="content-wrapper">

        <div *ngIf="isUserActive" class="main-ui">

            <div class="btn" title="Remove Visuals" (click)="collapseVisuals($event)">&#x2715;</div>
            <div class="btn" title="Download Visual" (click)="saveVisuals($event)">I</div>
            <div class="btn" title="Visuals On/Off" (click)="toggleVisuals($event)">V</div>
            <div class="btn" title="Open visuals in new window" (click)="openVisualsInNewWindow($event)">W</div>

            <div class="btn" title="Menu On/Off" (click)="toggleMenu($event)" style="float:right;"></div>

        </div>

        <div class="footer-ui">
                
            <div class="btn" title="Undo" (click)="onUndo($event)">Un</div>
            <div class="btn" title="Redo" (click)="onRedo($event)">Re</div>

        </div>

        <div id="p5-canvas-cont"></div>

        <div class="synthesizer-wrapper" [class.screen-offset]="!isCollapsed">

            <sy-synthesizer [synthesizer]="synthesizer"/>

        </div>

    </div>

  </div>

    
  
  `,
  styles: `
  
  
  .app-wrapper {

      position: relative;
  }

  .app-wrapper .content-wrapper {
      
      position: relative;
      width: 100%;
      height: 100vh;
  }

  .main-ui {

      position: relative;
      z-index: 5;
  }

  .footer-ui {

      z-index: 5;

      width: 10%;

      display: flex;
      justify-content: space-evenly;

      position: absolute;
      left: 50%;
      top: 0px;
  }

  .synthesizer-wrapper {

      position: absolute;

      top: 25px;
      left: 0px;

      width: 100%;
  }

  .synthesizer-wrapper.screen-offset {

      top: 100vh;
  }

  .svg-line {

      position: absolute;
      left: 0px;
      top: 0px;

      display: block;

      width: 100%;
      height: 100%;
  }

  
  `
})
export class AppComponent implements AfterViewInit, OnDestroy{

    synthesizer: Synthesizer

    private storedMuteState: boolean

    /** Menu open/close flag */
    public isMenuOpen = false

    public isUserActive: boolean = false
    private lastActiveTime = Date.now()
    private timeTillInactive = 1000 * 3
    private AFID: number


    constructor(private ngZone: NgZone) {

      // Create Synthesizer
      this.synthesizer = G.synthesizer = new Synthesizer()

      this.storedMuteState = !this.synthesizer.isMuted

      BeatMachine.subscribeTimeLine((t) => {

      })
    }

    // On document ready
    ngAfterViewInit() {

        // document.addEventListener('pointermove', onMouseMove)


        // Init globals
        G.init()
        G.w = window.innerWidth
        G.h = window.innerHeight

        

        // DB.get('sample').then((d) => {

        //     console.log('DB', d)
        // })
        
        // Create Visuals
        // let IID = setInterval(() => {

        //     const rnd = Math.round(Math.random() * 3)

        //     Visual.activeVisual.remove()

        //     console.log('rnd', rnd)
        //     switch(rnd) {

        //         case 0:
        //             Visual.flowField()
        //         break
        //         case 1:
        //             Visual.noise()
        //         break
        //         case 2:
        //             Visual.moire()
        //         break
        //         case 3:
        //             Visual.flowField()
        //         break
        //     }

        // }, 1000)

        // Visual.moire()
        Visual.flowField()
        // Visual.noise()

        // Set initial volume
        this.synthesizer.setVolume(-3)

        // Safari css support
        if(isSafari()) { document.body.classList.add('safari') }


        // Add midi support
        Midi.init((e: NoteMessageEvent) => {

          // @ts-ignore
            this.synthesizer.triggerAttack(e.note.identifier, Tone.getContext().currentTime, this.synthesizer.channel, e.note.velocity)
            
        },
        (e) => {
    
            this.synthesizer.triggerRelease(e.note.identifier, Tone.getContext().currentTime, this.synthesizer.channel)
        })


        // // Scroll to bottom
        // setTimeout(() => {

        //     window.scrollTo({
        //         top: 100000000,
        //         left: 0,
        //         behavior: 'smooth',
        //     })

        // }, 1500)


        /** LOAD FROM LOCAL STORAGE */
        const storageData = Storage.load()

        if(storageData) this.serializeIn(storageData, true)

        else this.serializeIn(DEFAULT_SESSION, false)

        // Save Undo
        Storage.saveUndo(storageData)
        

        
        // Change Background Colors
        let colors = JSON.parse(JSON.stringify(COLORS))
        colors.sort(() =>  Math.ceil((Math.random() * 2) - 1) )
        
        let i = 0

        setInterval(() => {

            if(i >= colors.length) { 
                
                i = 0
                colors.sort(() =>  Math.ceil((Math.random() * 2) - 1))
            }

            // console.log('col', colors[i])
            document.body.style.backgroundColor = colors[i]

            i++

        }, 20000 * (Tone.Transport.bpm.value * .01))



        document.addEventListener('visibilitychange', (e) => {
            
            if (document.visibilityState == "visible") {
                
                this.toggleActive(this.storedMuteState)
            }
            else {
                
              this.storedMuteState = !this.synthesizer.isMuted
              this.toggleActive(false)
            }
        })
        // Enter/Leave browser
        window.addEventListener('focus', () => this.toggleActive(this.storedMuteState))
        window.addEventListener('blur', () => {

            this.storedMuteState = !this.synthesizer.isMuted
            this.toggleActive(false)
        })

        // Browser resize event
        window.addEventListener('resize', () => {
        
            G.w = window.innerWidth
            G.h = window.innerHeight
        })
        
        // ON UNLOAD
        window.onbeforeunload = () => {

            Storage.save(this.serializeOut())

            this.synthesizer.mute(true)
        }

        document.addEventListener('click', () => {
            
          if(G.isPlaying) {
  
              G.start()
          }
  
          // console.log('click', synthesizer.presetManager.getPresets())
  
          // synthesizer.tracks.forEach(track => {
  
          //     console.log('Instrument', track.instrument.name, track.instrument.connectedInputs, track.instrument.connectedOutputs)
          //     track.nodes.forEach(node => {
  
          //         console.log('Node', node.name, node.connectedInputs, node.connectedOutputs)
          //     })
          // })
      })
  
      this.ngZone.runOutsideAngular(() => {
      
        this.activityUpdate()
      })
    }

    ngOnDestroy() {

        // if(IID) clearInterval(IID)
    }

    get isCollapsed() {

      return Visual.collapsed
    }

    // ON CHANGE TAB
    toggleActive = (active:boolean) => {

        if (active) {

            this.synthesizer.mute(false)
            
            Visual.visualsEnabled = true
            
        }
        else {

            this.synthesizer.mute(true)

            Visual.visualsEnabled = false
        }

        this.synthesizer = this.synthesizer
    }

    /** Toggle menu open/close */
    toggleMenu = (e) => {

        this.isMenuOpen = !this.isMenuOpen
    }

    /** Open visuals in new window */
    openVisualsInNewWindow = (e) => {

        Visual.openInNewWindow()
    }

    /** Enable/Disable Visuals*/
    toggleVisuals = (e) => {

        Visual.visualsEnabled = !Visual.visualsEnabled
    }
    
    /** Save image of visuals */
    saveVisuals = (e) => {

        Visual.visualsEnabled = false

        G.saveVisuals()

        Visual.visualsEnabled = true
    }

    /** Collapse visuals container */
    collapseVisuals = (e) => {

        Visual.collapsed = !Visual.collapsed

        if(Visual.activeVisual) {

            if(Visual.collapsed) Visual.activeVisual.remove()
            else Visual.activeVisual.restart()
        }
        else Visual.moire()
    }

    onUndo = (e) => {

        this.synthesizer.serializeIn(JSON.parse(Storage.undo()))
    }

    onRedo = (e) => {

        this.synthesizer.serializeIn(JSON.parse(Storage.redo()))
    }



    // Serialize
    serializeIn = (file: any, isString: boolean = false) => {
        
        // file = ''
        if(file == undefined) return
    
        let o: ISynthesizerSerialization

        if(isString) o = JSON.parse(file)
        else o = file

        console.log('Serialize In', o)
    
        this.synthesizer.serializeIn(o)
    }
    // TODO - MAKE VERSIONING HERE TOO FRO COMPATIBILITY
    serializeOut = () => {
    
        let o = this.synthesizer.serializeOut()
    
        return JSON.stringify(o)
    }


    @HostListener('document:pointermove')
    onMouseMove = (e) => {

        this.isUserActive = true

        this.lastActiveTime = Date.now()
    }

    activityUpdate = () => {

        if(this.lastActiveTime + this.timeTillInactive < Date.now()) {
            
            this.isUserActive = false
        }
        // console.log('requestAnimationFrame', NgZone.isInAngularZone())
        
        window.cancelAnimationFrame(this.AFID)
        this.AFID = window.requestAnimationFrame(this.activityUpdate.bind(this))
    }
  }

// src/App.svelte

<script lang="ts">
    
    import * as Tone from 'tone'
    import { WebMidi, type NoteMessageEvent } from "webmidi";

    import { onMount } from 'svelte';
    import Synthesizer from './app/view/Synthesizer.svelte'
    
    import { Synthesizer as Synth, type ISynthesizerSerialization } from './app/synthesizer'
    import { Storage } from './app/util/storage'
    import { G } from './app/core/globals'
    
    import { Visual } from './app/p5/visual'
    import { Track } from './app/track';
    import { Vec2 } from './app/util/math';

    import { DEFAULT_SESSION } from './app/presets';
    import { Midi } from './app/core/midi';
    import { isSafari } from './app/util/browser';


    // Init globals
    G.init()
    
    // Create Synthesizer
    let synthesizer = G.synthesizer = new Synth()

    // Create Visuals
    let activeVisual = Visual.moire()

    let storedMuteState = !synthesizer.isMuted


    // On document ready
    onMount(() => {

        synthesizer.setVolume(0)

        if(isSafari()) { document.body.classList.add('safari') }

        Midi.init((e: NoteMessageEvent) => {

            synthesizer.triggerAttack(e.note.identifier, Tone.now(), synthesizer.channel, e.note.velocity)
            
        },
        (e) => {
    
            synthesizer.triggerRelease(e.note.identifier, Tone.now(), synthesizer.channel)
        })

        // Scroll to bottom
        setTimeout(() => {

            window.scrollTo({
                top: 1000,
                left: 0,
                behavior: 'smooth',
            })

        }, 1500)

        /**
         * 
         *  RGB
         * 
'rgb(128, 122, 255)',
'rgb(255, 121, 159)',
'rgb(128, 255, 255)',
'rgb(255, 255, 159)',
'rgb(21, 111, 74)',
'rgb(105, 22, 22)',
'rgb(22, 22, 74)',
'rgb(22, 22, 22)',
'rgb(105, 111, 22)',
'rgb(105, 22, 74)',
'rgb(21, 111, 23)',
         */

        let i = 0
        let colors = [
            
            // '#FFFFFF', '#FFFF00', '#00FFFF', '#FF00FF', '#FF0000', '#00FF00',
    
            //   Cyan        Black      Red      blue
            '#166f4a', '#161616', '#691616', '#16164a',
            // 'rgb(128, 122, 255)',
            'rgb(255, 121, 159)',
            'rgb(128, 255, 255)',
            'rgb(255, 255, 159)',
            'rgb(21, 111, 74)',
            'rgb(105, 22, 22)',
            'rgb(22, 22, 74)',
            'rgb(22, 22, 22)',
            // 'rgb(105, 111, 22)',
            'rgb(105, 22, 74)',
            'rgb(21, 111, 23)',
        ]


        // colors = [ 'rgb(128, 255, 255)' ]


        // synthesizer.startSequence(0, ['F#2', 'D1', 'F#2', 'C#3'])

        // synthesizer.startSequence(1, ['A3', 'D3', 'E3', 'B3'])

        // synthesizer.startSequence(2, [['A3', 'E4'], 'A4', 'E4', 'D3'])

        // synthesizer.startSequence(3, [['A3', 'E4'], ['D3', 'B4'], ['D3', 'A4'], ['E3', 'B4']])



        // Colors
        colors.sort(() =>  Math.ceil((Math.random() * 2) - 1) )

        setInterval(() => {

            if(i >= colors.length) { 
                
                i = 0 
                colors.sort(() =>  Math.ceil((Math.random() * 2) - 1) )
            }

            // console.log('col', colors[i])
            document.body.style.backgroundColor = colors[i]

            i++

            synthesizer = synthesizer

        }, 30000)
    })
    


    // ON CHANGE TAB
    
    const toggleActive = (active:boolean) => {

        let nsd = Tone.Transport.nextSubdivision('8n')

        
        if (active) {
            // console.log('activate')
            
            synthesizer.mute(false)
            
            // Tone.Transport.start(nsd)
            
            Visual.visualsEnabled = true
            
        }
        else {
            // console.log('deactivate')
            
            // synthesizer.releaseKeys()
            synthesizer.mute(true)
            
            // Tone.Transport.pause(nsd)
            // Tone.Transport.stop(nsd)
            // Tone.Transport.cancel(nsd)

            // TODO - NOT RELEASING KEYS


            Visual.visualsEnabled = false
        }

        synthesizer = synthesizer
    }
    document.addEventListener('visibilitychange', (e) => {
        
        if (document.visibilityState == "visible") {
            
            toggleActive(storedMuteState)
        }
        else {
            
            storedMuteState = !synthesizer.isMuted
            toggleActive(false)
        }
    })
    window.addEventListener('focus', () => toggleActive(storedMuteState))
    window.addEventListener('blur', () => {

        storedMuteState = !synthesizer.isMuted
        toggleActive(false)
    })

    
    window.addEventListener('resize', () => {
    
        G.w = window.innerWidth
        G.h = window.innerHeight
    })
    
    // ON UNLOAD
    window.onbeforeunload = () => {

        Storage.save(serializeOut())

        synthesizer.mute(true)

        synthesizer = synthesizer
    }



    const toggleVisuals = (e) => {

        Visual.visualsEnabled = !Visual.visualsEnabled
    }
    
    const saveVisuals = (e) => {

        Visual.visualsEnabled = false

        G.saveVisuals()

        Visual.visualsEnabled = true
    }

    const collapseVisuals = (e) => {

        Visual.collapsed = !Visual.collapsed

        if(Visual.activeVisual) {

            if(Visual.collapsed) Visual.activeVisual.remove()
            else Visual.activeVisual.restart()
        }
        else Visual.moire()

        console.log('COLL', Visual.collapsed)
    }


    document.addEventListener('click', () => {

        Tone.start()
        Tone.Transport.start()

        // console.log('click')

        // let s = new Tone.PolySynth(Tone.DuoSynth).toDestination()

        // let seq = new Tone.Sequence((time: number, note: Tone.Unit.Frequency) => {

        //     console.log('yo',time, note)

        //     s.triggerAttackRelease(note, .1, Tone.now())

        // }, [['A3', 'A3'], ['F3', 'F3', 'F3'], ['D3', 'D3', 'D3', 'D3', 'D3', 'D3']], '4n')

        // seq.start(Tone.now())
    })


    // Serialize
    const serializeIn = (file: any, isString: boolean = false) => {

        // file = ''
        if(file == undefined) return
    
        let o: ISynthesizerSerialization

        if(isString) o = JSON.parse(file)
        else o = file
    
        synthesizer.serializeIn(o)

        synthesizer = synthesizer
    }
    
    const serializeOut = () => {
    
        let o = synthesizer.serializeOut()

        // {
        //     synthesizer: o,
            // eppilepsyMessage: 
        // }
    
        return JSON.stringify(o)
    }


    /** LOAD FROM LOCAL STORAGE */
    const storageData = Storage.load()

    if(storageData) serializeIn(storageData, true)

    else serializeIn(DEFAULT_SESSION, false)

    synthesizer = synthesizer
    
    


</script>


{#if !G.fullScreenmode }

<div class="main-ui">

    <div class="btn" on:click={collapseVisuals}>&#x2715;</div>
    <div class="btn" on:click={saveVisuals}>I</div>
    <div class="btn" on:click={toggleVisuals}>V</div>

</div>

{/if}

<div class="synthesizer-wrapper" class:screen-offset={!Visual.collapsed}>

    <Synthesizer synthesizer={synthesizer}>
    <!-- on:mousemove={onMouseMove} -->

    <!-- 
        
        <svg class="svg-line">
            
            <line x1={mousePosition.x} y1={mousePosition.y} x2={elementPosition.x} y2={elementPosition.y} stroke="#FFFFFF"></line>
        </svg> -->
        
        
    </Synthesizer>

</div>


<style>

    .main-ui {


    }

    .synthesizer-wrapper {

        position: absolute;

        top: 25px;
        left: 0px;

        width: 100%;
    }

    .synthesizer-wrapper.screen-offset {

        top: 100vh;
    }

    .svg-line {

        position: absolute;
        left: 0px;
        top: 0px;

        display: block;

        width: 100%;
        height: 100%;
    }

</style>
